- go.sum
- internal/provider/common.go
- internal/provider/network.go
- internal/provider/provider.go
- internal/provider/resource_deployment.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
- internal/provider/utils.go
- fix timeouts to avoid waiting infinitely when rmb fails to start.
- enhance initial check to validate nodes, and link to troubleshooting link
- refactoring
- better handling of state and bug fixes regarding contract-leaking when the deployments fails
- add zdb namespaces and ips.
> Bug fixes and code refactor.

- examples/resources/singlenode/main.tf
- internal/provider/resource_deployment.go
Still missing fetching it from the workload data.
Blocked on https://github.com/threefoldtech/zos/issues/1395
> Add vm yggdrasil info

- internal/provider/common.go
- internal/provider/resource_deployment.go
and a small fix to the planetary reading
> Update substrate contract calls, planetary fix

- go.mod
- go.sum
- internal/node/node.go
to remove zos pkg dependency to fix darwin build
> use tf PublicConfig

- internal/provider/resource_scheduler.go
- internal/rmbproxy/rmbproxytypes.go
- change node state to node status to align with new grid proxy
> change node state to node status to align with new grid proxy

- internal/provider/resource_network.go
> validate network subnet should be 16

- examples/resources/k8s/main.tf
> Modify k8s example to have wg access

- examples/resources/expose-vm/main.tf
> Adds an example to expose a vm

- examples/resources/multinode/main.tf
> Adds public ips to mutlinode example

- examples/resources/peertube/main.tf
> Adds peertube example

- examples/resources/peertube/main.tf
> Adds email setting for peertube

- examples/resources/peertube/main.tf
> Adds deploy peertube with yggdrasil ip

- examples/resources/k8s-with-domain/main.tf
> Adds kuberntes example with domain using gateway

- examples/resources/external_provisioner/main.tf
> Adds example using terraform provisioner

- examples/resources/external_provisioner/main.tf
> change provisioner flist to ubuntu

- docs/resources/deployment.md
- docs/resources/kubernetes.md
- internal/provider/common.go
- internal/provider/provider.go
- internal/provider/resource_deployment.go
- internal/provider/resource_k8s.go
resolves https://github.com/threefoldtech/terraform-provider-grid/issues/158
> add public ipv6 support

- docs/index.md
- internal/provider/provider.go
to merge after gridprox is deployed
> add mainnet & upgrade substrate client

- examples/resources/taiga/main.tf
Example HCL file for deploying taiga VM on grid3, with required mount and Env variables.
> Adding taiga example

- go.mod
- go.sum
- internal/gridproxy/grid_client.go
- internal/gridproxy/types.go
- internal/node/proxy.go
- internal/provider/common.go
- internal/provider/provider.go
- internal/provider/resource_scheduler.go
- internal/provider/validation.go
rmb-go to be added to go.sum once merged
> update signature and proxy breaking changes

- examples/resources/mattermost/main.tf
_Signed-off-by:_ Ashraf Fouda <ashraf.m.fouda@gmail.com>
> Adds mattermost example

- examples/resources/cosmosvalidator/main.tf
> Adds cosmos validator example

- internal/provider/resource_k8s.go
> updates k8s image

- internal/provider/resource_deployment.go
> Adds corex support

- examples/resources/presearch/main.tf
related issues:
- https://github.com/threefoldtech/terraform-provider-grid/issues/238
> update presearch comment

- internal/node/node.go
- pkg/deployer/deployer.go
> disk upgrades not applying issue fix

- .github/workflows/terratest.yml
- Removed unused part in the workflow.
- Updated the directory in the go test command
> Fix terratest workflow

- .github/workflows/terratest.yml
- README.md
- Changed the workflow to use gotestsum for a better looking test output.
- Updated the readme with the correct commands to run the tests
https://github.com/threefoldtech/test_feedback/issues/271
> Change the workflow to use gotestsum & update the readme

- internal/provider/resource_k8s.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/289
> add k8s node token validation

- examples/resources/cosmosvalidator/main.tf
- examples/resources/expose-vm/main.tf
- examples/resources/k8s-with-domain/main.tf
- examples/resources/k8s/main.tf
- examples/resources/mattermost/main.tf
- examples/resources/peertube/main.tf
- examples/resources/presearch/main.tf
- examples/resources/singlenode/main.tf
- examples/resources/taiga/main.tf
- internal/provider/deployment.go
- internal/provider/gateway_fqdn.go
- internal/provider/gateway_name.go
- internal/provider/resource_deployment.go
- internal/provider/resource_gateway_fqdn.go
- internal/provider/resource_gateway_name.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
- pkg/deployer/deployer.go
- pkg/deployer/deployer_test.go
> Adds solution type

- examples/resources/nixos-micro/main.tf
> Adds nixos example

- examples/resources/nixos-micro/main.tf
> updates nixos

- internal/provider/resource_network.go
- (https://github.com/threefoldtech/terraform-provider-grid/issues/353)
> fixes wgconfig disappearing issue

- examples/resources/nixos-micro/main.tf
> removes deployment name for nixos example

- internal/provider/provider.go
- internal/provider/provider_test.go
- main.go
- (https://github.com/threefoldtech/terraform-provider-grid/issues/364)
> Initiates substrate connection in providerConfigure

- go.mod
- go.sum
- (https://github.com/threefoldtech/terraform-provider-grid/issues/371)
> upgrade go_substrate_rpc_client

- tests/VM_with_planetary_network/main.tf
- tests/gateway_with_yggdrasil_ip/main.tf
- tests/kubernetes/main.tf
- tests/kubernetes_with_2worker_same_name/main.tf
- tests/kubernetes_with_k8s_module/kubernetes_test.go
- tests/kubernetes_with_k8s_module/main.tf
- tests/kubernetes_with_no_network/main.tf
- tests/mattermost/main.tf
- tests/mattermost/mattermost_test.go
- tests/mount_with_file_bigger_than_disk_size/main.tf
- tests/mounts/main.tf
- tests/multinode/main.tf
- tests/peertube/main.tf
- tests/peertube/peertube_test.go
- tests/presearch/main.tf
- tests/presearch/presearch_test.go
- tests/qsfs_check_metrics/main.tf
- tests/qsfs_read_write/main.tf
- tests/singlenode/main.tf
- tests/singlenode_key_ed25519/main.tf
- tests/singlenode_with_memory_less_than_250M/main.tf
- tests/singlenode_with_zero_cpu/main.tf
- tests/taiga/main.tf
- tests/taiga/taiga_test.go
- tests/zdbs/main.tf
provided new tests and fixed the old tests to the latest updates
#368
> fixed terra tests and new tests

- internal/provider/errors.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
> added k8s updates

- internal/provider/resource_k8s.go
> adds ip validation check in getK8sFreeIP

- .github/workflows/lint.yml
- internal/node/client_pool.go
- internal/node/node.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/463
> go routine of are nodes up

- internal/node/node.go
- pkg/deployer/deployer.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/462
> go routine of get deployments

- internal/provider/data_source_gateway_domain.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
- internal/provider/resource_scheduler.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/464
> api client interface casting

- examples/resources/forwarder/main.tf
- https://github.com/threefoldtech/terraform-provider-grid/issues/471
> forwarder_example

- internal/node/proxy.go
- pkg/workloads/flist.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/479
> close response body

- internal/provider/resource_scheduler.go
fixes a typo in the scheduler resource
> reource -> resource typo

- wiki/release.md
List of changes this PR includes
> Adds release workflow

- go.mod
- go.sum
- internal/node/node.go
netlink import problem
remove zos import and add a version struct
> remove zos import - netlink

- .github/workflows/test.yml
- wiki/workflows.md
Signed-off-by: mario <mariobassem12@gmail.com>
checks if the provider builds on all supported platforms on development merges
added build commands in test.yaml workflow
(https://github.com/threefoldtech/terraform-provider-grid/issues/495)
> builds the terraform provider on all platforms on development merges

- internal/provider/deployment.go
- internal/provider/deployment_test.go
- internal/provider/mocks/local_state_mock.go
- internal/provider/resource_deployment.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
- pkg/state/network_state.go
- pkg/state/state_test.go
- pkg/state/types.go
This PR is readability refactor on the deployer mainly specifying HostIDs instead NodeIPs
will be followed up with #502 to fix the factory functions and interfaces around it
> refactor deployer

- GNUmakefile
- integrationtests/gateway_name/main.tf
- integrationtests/gateway_with_fqdn/main.tf
- integrationtests/k8s/main.tf
- integrationtests/k8s_invalid_names/main.tf
- integrationtests/k8s_test.go
- integrationtests/k8s_using_module/main.tf
- integrationtests/mattermost/main.tf
- integrationtests/peertube/main.tf
- integrationtests/presearch/main.tf
- integrationtests/qsfs/main.tf
- integrationtests/taiga/main.tf
- integrationtests/vm/main.tf
- integrationtests/vm_invalid_cpu/main.tf
- integrationtests/vm_invalid_memory/main.tf
- integrationtests/vm_mount_invalid_write/main.tf
- integrationtests/vm_mounts/main.tf
- integrationtests/vm_multinode/main.tf
- integrationtests/vm_public_ip/main.tf
- integrationtests/wireguard/main.tf
- integrationtests/zdbs/main.tf
(https://github.com/threefoldtech/terraform-provider-grid/issues/511)
> Use scheduler in integration tests

- internal/provider/resource_network.go
> fixes #541

- examples/resources/k8s/main.tf
Fixes k8s deployment example.
Removes undefined values and replace them with hardcoded values.
> fix k8s example

- internal/node/node.go
- internal/provider/data_source_gateway_domain.go
- internal/provider/resource_network.go
- pkg/deployer/deployer.go
> adds default timeouts to nodeclient calls

- go.mod
- go.sum
- pkg/subi/manager.go
- pkg/subi/substrate.go
- (https://github.com/threefoldtech/terraform-provider-grid/issues/12)
> supports provider parallelism

- examples/resources/singlenode/main.tf
> fix single node plugin source

- internal/provider/provider.go
- (https://github.com/threefoldtech/terraform-provider-grid/issues/572)
> add qa relay link

- README.md
- integrationtests/gateway_test.go
- integrationtests/k8s_test.go
- integrationtests/mattermost_test.go
- integrationtests/peertube_test.go
- integrationtests/presearch_test.go
- integrationtests/qsfs_test.go
- integrationtests/taiga_test.go
- integrationtests/vm_test.go
- integrationtests/wireguard_test.go
- (https://github.com/threefoldtech/terraform-provider-grid/issues/571)
> remove parallelism=1 from tests and docs

- internal/provider/provider.go
List of changes this PR includes
> Adds testnet relayurl

- examples/resources/deployment_resource.tf
- examples/resources/k8s-using-modules/main.tf
- examples/resources/k8s-with-domain/main.tf
- examples/resources/k8s/main.tf
- examples/resources/mattermost/main.tf
- examples/resources/peertube/main.tf
- examples/resources/presearch/main.tf
- examples/resources/simple-dynamic/main.tf
- examples/resources/taiga/main.tf
updates examples to use ssh pub key from .ssh dir as a default value
> updates example to use ssh pubkey from .ssh dir

- internal/provider/deployment.go
- https://github.com/threefoldtech/terraform-provider-grid/issues/606
> check sol provider before parsing

- examples/resources/k8s-using-modules/main.tf
List of changes this PR includes
> Adds output from k8s module

- internal/provider/deployment.go
> assign NodeDeploymentID field when reading deployment from tf files

- GNUmakefile
- https://github.com/threefoldtech/terraform-provider-grid/issues/634
> clean test dirs and build befor integration

- integrationtests/k8s/main.tf
- integrationtests/k8s_test.go
- integrationtests/vm/main.tf
- integrationtests/vm_invalid_cpu/main.tf
- integrationtests/vm_invalid_memory/main.tf
tests can use the right units in scheduler for tests 
#603 
#369
> fixing scheduler setup for tests

- .github/workflows/terratest.yml
fixes for nightly tests and added tests to all versions and networks
#634
> tests for nightly

- docs/resources/private_gateway.md
- integrationtests/gateway_name_private/main.tf
List of changes this PR includes
- https://github.com/threefoldtech/info_grid/issues/118
> Adds private gateway docs

- internal/provider/provider.go
- internal/provider/resource_deployment.go
- internal/provider/resource_gateway_fqdn.go
- internal/provider/resource_gateway_name.go
- internal/provider/resource_k8s.go
- internal/provider/resource_network.go
Add resource validation.
- Add key type and network check.
- Add CPU, RAM, Disk check.
- Add IP Range check.
- Add K8s token check.
- Add some URLs check.
- https://github.com/threefoldtech/terraform-provider-grid/issues/671
> Add resources validation

- .goreleaser.yml
- add 1,9,2 branch
- format yml file just to add the branch :)
> fmt goreleaser

- .github/workflows/terratest.yml
- integrationtests/k8s_test.go
- integrationtests/wireguard_test.go
skips failing tests and fixed timeout issue
#770 #769 #658
> Fixing nightly tests

- .github/workflows/terratest.yml
- https://github.com/threefoldtech/terraform-provider-grid/issues/778
> fix ygg in workflow

- examples/resources/nomad_with_modules/main.tf
- modules/nomad-module/main.tf
- modules/nomad-module/output.tf
- modules/nomad-module/variables.tf
Add nomad module to simplify deploying a Nomad cluster.
- #765
> create nomad module

- go.mod
- go.sum
Update grid-client to 0.11.9
- #803
> Update grid client

- README.md
- https://github.com/threefoldtech/terraform-provider-grid/issues/781
> add private ips issue in readme

- modules/nomad-module/main.tf
Fix Nomad module server flist.
- #765
> Fix server flist

- integrationtests/nomad_test.go
- integrationtests/nomad_using_module/main.tf
- integrationtests/remoterun.go
- integrationtests/units.go
> add nomad module integration test
